// $Id$

#ifndef EXAMPLE_SCANNER_H
#define EXAMPLE_SCANNER_H

// Flex expects the signature of yylex to be defined in the macro YY_DECL, and
// the C++ parser expects it to be declared. We can factor both as follows.
#undef YY_DECL
#ifndef YY_DECL

#define	YY_DECL						\
    NS_AMS8051HEX::Parser::token_type				\
    NS_AMS8051HEX::Scanner::lex(				\
    NS_AMS8051HEX::Parser::semantic_type* yylval,		\
    NS_AMS8051HEX::Parser::location_type* yylloc		\
    )
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer ASMFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

#include "parser.h"

namespace NS_AMS8051HEX {

/** Scanner is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to ExampleFlexLexer. However we change the context of the generated
 * yylex() function to be contained within the Scanner class. This is required
 * because the yylex() defined in ExampleFlexLexer has no parameters. */
class Scanner : public ASMFlexLexer
{
public:
    /** Create a new scanner object. The streams arg_yyin and arg_yyout default
     * to cin and cout, but that assignment is only made when initializing in
     * yylex(). */
    Scanner(class Driver& drv, std::istream* arg_yyin = 0,
	    std::ostream* arg_yyout = 0);

    /** Required for virtual functions */
    virtual ~Scanner();

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual Parser::token_type lex(
	Parser::semantic_type* yylval,
	Parser::location_type* yylloc
	);

    /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    void set_debug(bool b);

    //2020.12.18 在scanner中添加pdriver，用于在词法解析中，调用上层代码context
    class Driver& driver;
public:
    //skip comment start with "/*" and end with "*//"
    void skip_comment(Parser::location_type* yylloc);

    //Parser::token_type multi_line_string(Parser::semantic_type* yylval, Parser::location_type* yylloc);

    class comp_context *pcompi;
};

} // namespace example

#endif // EXAMPLE_SCANNER_H
