#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer ASMFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::istream* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
/* %endif */

void *ASMalloc (yy_size_t  );
void *ASMrealloc (void *,yy_size_t  );
void ASMfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[312] =
    {   0,
        0,    0,  116,  114,  113,   84,   95,  114,  112,   76,
      101,   94,  114,  107,  108,   99,   98,  109,   97,   93,
      100,   88,   87,   87,  110,    1,  102,  111,  103,  106,
      114,    2,   85,    3,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
      104,   85,  105,   96,  113,    0,   92,    0,    0,    0,
        0,   88,   88,    0,   91,   90,   88,   88,    0,   88,
       87,   87,   87,   87,   87,   87,   87,   87,   83,   82,
        0,    0,    0,   85,    4,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   27,

       65,   85,   85,   85,   85,   85,   85,   85,   85,   32,
       34,   85,   85,   39,    0,    0,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   11,   12,   13,   14,   15,
       16,   17,   18,   85,   52,   54,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   92,
        0,    0,    0,    0,    0,   89,    0,    0,   88,   88,
       88,    0,    0,    0,   91,   88,   88,   88,   88,   86,
       87,   87,   87,   87,   87,   87,   87,   87,    0,    0,
        9,   10,   85,   20,   85,   85,   85,   23,   85,   85,
       70,   85,   85,   25,   26,   85,   28,   29,   85,   85,

       69,   68,   85,   31,   33,   35,   36,   37,   38,   85,
       85,   79,   81,   42,   45,   46,   77,   72,   47,   48,
       85,   50,   53,   55,   85,   85,   73,   80,   85,   85,
       85,   85,   85,   60,   85,   62,    0,    0,    0,    0,
        0,   88,   88,   88,   88,    0,    0,    0,    0,   88,
       86,   86,   86,   87,   87,    0,    0,    0,   85,   21,
       22,   85,   63,   24,   66,   30,    6,   78,   85,   41,
       43,   44,   49,   51,   71,   56,   85,   57,   58,   59,
       85,   61,   85,    0,    0,    0,    0,    0,   88,    0,
       86,   86,   86,   86,    0,    7,    5,   19,   40,   85,

       75,   67,    0,   86,    0,   85,    0,    8,   64,   74,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   46,   60,
        1,   61,    1,   62,   46,    1,   63,   64,   65,   65,

       65,   63,   46,   66,   46,   46,   46,   67,   46,   68,
       46,   46,   46,   68,   46,   68,   69,   68,   46,   70,
       46,   46,    1,   71,    1,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    4,    4,    4,    5,    5,    5,    5,    5,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[318] =
    {   0,
        0,    0,  760,  911,   71,   73,  911,   72,  911,  706,
      911,  911,  676,  911,  911,  911,  911,  911,  911,  911,
      911,  115,  167,   59,  911,  911,  705,  911,  700,  911,
       44,  218,   49,   63,   80,  252,  127,    0,  688,  682,
      164,  288,   34,  678,  674,   35,  320,  262,  163,  106,
      911,  122,  911,  911,   79,   87,  306,  371,  676,   85,
      437,   52,  310,  489,    0,  911,  361,  284,    0,  345,
        0,    0,  408,  386,  430,  153,  182,  422,  911,  911,
      706,  668,   84,  399,  431,  480,  483,    0,    0,  668,
      483,  667,  249,  481,  643,  516,  647,  517,  646,  529,

      542,  551,  625,  632,  623,  637,  619,  611,  610,  607,
        0,  589,  123,    0,  102,  572,  596,  581,  570,  118,
      555,   54,  169,  550,  545,    0,    0,    0,    0,    0,
        0,    0,    0,  542,  555,  554,  533,  520,  518,  515,
      503,  496,  505,  502,  491,  490,  495,  480,  518,  538,
      498,  142,  590,    0,  447,  911,  598,    0,  583,  270,
      588,  594,  318,  600,  911,  621,  438,  625,  539,  359,
      628,  561,  636,  637,  344,  154,  312,  184,  196,  438,
      911,  911,  668,  597,  441,  503,  155,    0,  356,  257,
        0,  652,  450,    0,    0,  449,  685,    0,  424,  429,

        0,    0,  436,    0,    0,    0,    0,    0,    0,  419,
      398,    0,    0,  276,    0,    0,    0,    0,    0,    0,
      403,  396,    0,    0,  366,  382,    0,    0,  363,  365,
      370,  351,  340,  344,  316,    0,  720,  777,  320,  728,
      833,  714,  306,  377,  643,  718,  320,  440,  645,  692,
      263,   83,  159,  722,  388,  317,  326,  305,  763,  730,
        0,  491,  764,    0,    0,    0,    0,    0,  309,    0,
        0,    0,    0,    0,    0,    0,  301,    0,    0,    0,
      310,    0,  298,  116,    0,  289,  157,    0,  595,  604,
      256,  911,  275,  228,  239,  911,  911,  765,    0,  244,

        0,    0,  255,  911,  200,  201,  179,  911,    0,  911,
      911,  898,  903,  905,  166,  109,   85
    } ;

static yyconst flex_int16_t yy_def[318] =
    {   0,
      311,    1,  311,  311,  311,  311,  311,  312,  311,  311,
      311,  311,  313,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,   23,  311,  311,  311,  311,  311,  311,
      311,  311,   32,   32,   32,   32,   32,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      311,  314,  311,  311,  311,  312,  311,  311,  311,  313,
      311,   22,   22,   63,   64,  311,  311,  311,  315,  311,
       23,   24,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,   32,   32,   32,   32,  314,  314,  314,
      314,  314,  314,  314,  314,   32,  314,  314,  314,   32,

       32,   32,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  312,  313,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  311,
      311,  311,  312,  316,  311,  311,  313,  317,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  315,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,   32,   32,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,   32,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  312,  312,  311,  313,
      313,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  314,   32,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  312,  238,  311,  313,  241,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  314,  314,  314,

      314,  314,  311,  311,  311,  314,  311,  311,  314,  311,
        0,  311,  311,  311,  311,  311,  311
    } ;

static yyconst flex_int16_t yy_nxt[984] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   24,   24,   24,   24,   24,   24,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   38,   42,   43,   44,   45,
       46,   38,   47,   48,   38,   49,   38,   38,   50,   38,
        4,   51,   37,   37,   37,   38,   38,   38,   52,   38,
       53,   54,   55,   55,   55,   55,   57,   72,   72,   81,
       55,   55,   82,  120,  124,   84,   84,   84,  241,  121,
      125,   57,   95,   88,  156,   64,   83,   88,   96,   84,

       84,   84,  181,  182,  216,   76,   57,   97,  217,   98,
      311,   88,  238,   99,   77,  100,  101,   84,   84,  102,
       57,  311,   64,  103,  104,   78,  115,   77,   88,  293,
      105,  116,   58,   62,   62,   63,   63,   63,   63,   63,
       63,   64,   64,  146,  147,   61,  115,   58,  149,  294,
       64,   65,   64,   64,   64,   64,  213,   66,  148,  207,
      208,   67,   58,   84,   84,   84,  156,  115,  151,  170,
       68,   88,  116,   69,  214,   88,   58,   64,   65,   64,
       66,   70,  209,   68,   69,   71,   71,   72,   72,   72,
       72,   72,   72,   72,   72,   66,   66,   89,  310,  175,

      110,  111,   64,   65,   64,   64,   64,   64,  176,   66,
      218,  112,  113,   73,  292,  219,  145,   61,   66,   66,
       89,  176,   74,  114,   66,  291,   66,  292,  177,   64,
       65,   64,   66,   75,  256,   74,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,  257,   66,  178,   66,
      255,  309,  308,   84,   85,   86,   87,   84,   84,   88,
       89,   88,   90,   88,   91,   88,   92,   88,   88,   88,
       88,   88,   88,   93,   88,   88,   88,   88,  307,  306,
       84,   84,   84,   89,   94,   88,   93,   88,   84,   84,
       84,   89,  115,  305,  304,  189,   88,  116,  137,   89,

      106,  138,  139,  107,  140,  141,  142,  150,  150,  291,
      115,  292,   66,  271,   89,  190,  244,  143,  292,  144,
      165,  304,   89,  262,  292,  117,   66,  303,   63,   63,
      168,  292,  118,  302,  272,   66,  245,  119,  126,  127,
      128,  129,  130,  131,  132,  133,   64,  165,   66,   66,
      169,  301,  151,  300,   66,  299,  159,  297,  255,  134,
       66,  151,   66,  296,  248,  160,  135,  295,  311,  286,
      283,   66,  136,   64,  152,   56,  161,   66,  160,  311,
       56,  165,  282,   66,  249,   66,   66,   66,  281,  153,
      153,  153,  153,  153,  153,  153,  153,  165,   89,  176,

      167,  280,  262,   66,   56,  251,  279,  166,  165,   66,
       66,  166,  176,  167,  252,  278,  167,  277,  276,   66,
      275,   89,  165,  289,  165,  253,   66,  252,   66,  167,
       66,   56,  173,   56,   56,   84,   84,   84,   56,  274,
      154,   60,   66,   88,  165,  273,   60,   88,  270,  165,
       66,   66,  174,   66,  171,  157,  157,  157,  157,  157,
      157,  157,  157,  172,   66,  269,  165,   84,   84,   84,
       60,  165,   66,   66,  165,   88,  172,  176,  268,   88,
       66,  267,   66,  266,  265,  172,  290,   66,  175,  264,
      176,  261,  258,  165,  239,   66,  171,   60,  172,   60,

       60,  165,  115,   66,   60,   66,  158,   64,   64,   64,
       64,   64,   64,   64,   64,  183,   84,   84,   84,   84,
       84,  184,  115,   89,   88,   89,  236,   88,   88,  186,
      235,   88,  234,   89,  233,  162,  187,  232,  187,  150,
      150,  231,  115,  230,  163,   89,   89,  186,   89,  187,
      229,  187,   84,   84,   84,  164,   89,  163,  187,   89,
       88,  228,  192,  186,   88,   84,   84,   84,   89,  194,
      227,  187,  187,   88,  226,  165,  225,   88,   84,   84,
       84,   66,   89,  196,  151,  187,   88,   84,  197,   84,
       88,  224,  223,  151,   57,   88,  222,  165,  221,   88,

      220,  215,  165,   66,   66,  250,  152,  156,  237,  237,
      237,  237,  237,  237,  237,  237,  240,  240,  240,  240,
      240,  240,  240,  240,  165,   66,   66,  212,  211,  242,
       66,  210,   61,   84,  260,   84,   66,   66,  243,  206,
      246,   88,   66,  243,  205,   88,   66,  204,   66,  247,
       58,  243,  203,   66,  242,  247,  243,  165,   61,   66,
       66,  165,  247,   66,  165,   66,  246,   66,  247,   66,
       66,  250,  165,  165,  202,  201,  167,  200,   66,   66,
      199,  198,  254,  172,  165,   66,   66,   66,  165,  167,
       66,  165,  195,   66,   89,  193,  172,  191,  263,  165,

      165,   66,   66,  254,   84,   84,   84,  187,   66,  289,
       66,  290,   88,  188,  259,  185,   88,   89,  180,  179,
      187,   84,   84,   84,   57,  155,  123,  122,  165,   88,
      109,  108,   80,   88,   66,   79,   61,  156,  284,  284,
      284,  284,  284,  284,  284,  284,  287,  287,  287,  287,
      287,  287,  287,  287,   59,  165,   66,   66,  165,  311,
       66,  311,  311,  311,   66,  311,   84,   84,   84,  243,
      311,  311,  311,  247,   88,  311,  311,  311,   88,   66,
       58,   57,  243,   66,  311,  165,  247,   66,   61,  311,
      311,  311,  311,  311,  311,  285,  285,  285,  285,  285,

      285,  285,  285,  285,  285,   89,   89,   89,  311,  298,
      311,  311,  285,  285,  285,  285,  285,  285,  187,  187,
      187,  311,  311,  311,  311,  311,  311,  311,   89,   89,
       89,  187,  187,  187,  311,  311,  311,   58,  311,  285,
      285,  285,  156,  311,  311,  311,  311,  311,  311,  311,
      311,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  311,  311,  311,  311,  311,  311,  311,  288,  288,
      288,  288,  288,  288,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,   61,  311,  288,  288,  288,   56,  311,

       56,   56,   56,   60,  311,  311,   60,   60,   88,   88,
        3,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311
    } ;

static yyconst flex_int16_t yy_chk[984] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    6,    8,   24,   24,   31,
       55,   55,   31,   43,   46,   33,   33,   33,  317,   43,
       46,   56,   33,   33,   60,   24,   31,   33,   34,   34,

       34,   34,   83,   83,  122,   24,  115,   34,  122,   34,
       62,   34,  316,   34,   24,   35,   35,   35,   35,   35,
      284,   62,   24,   35,   35,   24,   52,   24,   35,  252,
       35,   52,    8,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   50,   50,   60,  152,   56,   52,  252,
       22,   22,   22,   22,   22,   22,  120,   22,   50,  113,
      113,   22,  115,   37,   37,   37,  287,   49,  152,  315,
       22,   37,   49,   22,  120,   37,  284,   22,   22,   22,
       22,   22,  113,   22,   22,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   76,  176,  187,  307,   76,

       41,   41,   23,   23,   23,   23,   23,   23,   76,   23,
      123,   41,   41,   23,  253,  123,   49,  287,   76,  176,
      187,   76,   23,   41,   77,  253,  178,  253,   77,   23,
       23,   23,   23,   23,  179,   23,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,  179,   77,   77,  178,
      178,  306,  305,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,  303,  300,
       32,   32,   32,   32,   32,   32,   32,   32,   36,   36,
       36,   93,   42,  295,  294,   93,   36,   42,   48,  190,

       36,   48,   48,   36,   48,   48,   48,   57,   57,  251,
       57,  291,  160,  214,   93,   93,  160,   48,  251,   48,
       68,  293,  190,  190,  291,   42,   68,  286,   63,   63,
       68,  251,   42,  283,  214,  160,  160,   42,   47,   47,
       47,   47,   47,   47,   47,   47,   63,   68,  243,   68,
       68,  281,   57,  277,  177,  269,   63,  258,  177,   47,
      163,   57,  247,  257,  163,   63,   47,  256,   63,  239,
      235,  243,   47,   63,   57,   58,   63,  177,   63,   63,
       58,   70,  234,  163,  163,  247,  175,   70,  233,   58,
       58,   58,   58,   58,   58,   58,   58,   67,  189,  175,

       70,  232,  189,   67,   58,  170,  231,   67,   70,  175,
       70,   70,  175,   70,  170,  230,   67,  229,  226,  244,
      225,  189,   74,  244,   67,  170,   67,  170,   74,   67,
      255,   58,   74,   58,   58,   84,   84,   84,   58,  222,
       58,   61,  244,   84,   73,  221,   61,   84,  211,   74,
       73,   74,   74,  255,   73,   61,   61,   61,   61,   61,
       61,   61,   61,   73,   78,  210,   75,   85,   85,   85,
       61,   73,   75,   73,  167,   85,   73,   78,  203,   85,
      167,  200,  248,  199,  196,   75,  248,   78,   78,  193,
       78,  185,  180,   75,  155,   75,   75,   61,   75,   61,

       61,  167,  151,  167,   61,  248,   61,   64,   64,   64,
       64,   64,   64,   64,   64,   86,   86,   86,   86,   87,
       87,   87,  149,   94,   86,   91,  148,   87,   86,   91,
      147,   87,  146,  262,  145,   64,   94,  144,   91,  150,
      150,  143,  150,  142,   64,  186,   94,   94,   91,   94,
      141,   91,   96,   96,   96,   64,  262,   64,  186,   98,
       96,  140,   96,   98,   96,  100,  100,  100,  186,   98,
      139,  186,   98,  100,  138,  169,  137,  100,  101,  101,
      101,  169,   98,  100,  150,   98,  101,  102,  102,  102,
      101,  136,  135,  150,  153,  102,  134,  172,  125,  102,

      124,  121,  169,  172,  169,  169,  150,  157,  153,  153,
      153,  153,  153,  153,  153,  153,  157,  157,  157,  157,
      157,  157,  157,  157,  172,  159,  172,  119,  118,  159,
      161,  117,  116,  184,  184,  184,  162,  289,  159,  112,
      162,  184,  164,  161,  110,  184,  290,  109,  159,  162,
      153,  159,  108,  161,  161,  164,  161,  166,  157,  162,
      289,  168,  162,  166,  171,  164,  164,  168,  164,  290,
      171,  168,  173,  174,  107,  106,  166,  105,  173,  174,
      104,  103,  173,  171,  166,  245,  166,  249,  168,  166,
      168,  171,   99,  171,  192,   97,  171,   95,  192,  173,

      174,  173,  174,  174,  183,  183,  183,  192,  245,  245,
      249,  249,  183,   92,  183,   90,  183,  192,   82,   81,
      192,  197,  197,  197,  237,   59,   45,   44,  250,  197,
       40,   39,   29,  197,  250,   27,   13,  240,  237,  237,
      237,  237,  237,  237,  237,  237,  240,  240,  240,  240,
      240,  240,  240,  240,   10,  250,  242,  250,  254,    3,
      246,    0,    0,    0,  254,    0,  260,  260,  260,  242,
        0,    0,    0,  246,  260,    0,    0,    0,  260,  242,
      237,  238,  242,  246,    0,  254,  246,  254,  240,    0,
        0,    0,    0,    0,    0,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  259,  263,  298,    0,  259,
        0,    0,  238,  238,  238,  238,  238,  238,  259,  263,
      298,    0,    0,    0,    0,    0,    0,    0,  259,  263,
      298,  259,  263,  298,    0,    0,    0,  238,    0,  238,
      238,  238,  241,    0,    0,    0,    0,    0,    0,    0,
        0,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,    0,    0,    0,    0,    0,    0,    0,  241,  241,
      241,  241,  241,  241,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  241,    0,  241,  241,  241,  312,    0,

      312,  312,  312,  313,    0,    0,  313,  313,  314,  314,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311
    } ;

static yyconst flex_int16_t yy_rule_linenum[115] =
    {   0,
       97,   99,  100,  101,  102,  103,  104,  105,  106,  107,
      108,  109,  110,  111,  112,  113,  114,  115,  119,  120,
      121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
      131,  132,  133,  134,  135,  136,  137,  138,  139,  140,
      141,  142,  143,  144,  145,  146,  147,  148,  149,  150,
      151,  152,  153,  154,  155,  156,  157,  158,  159,  160,
      161,  162,  163,  164,  166,  167,  168,  169,  170,  171,
      172,  173,  174,  175,  176,  179,  180,  181,  182,  183,
      184,  186,  187,  189,  191,  224,  225,  226,  227,  228,
      229,  233,  237,  238,  239,  240,  242,  243,  244,  245,

      247,  248,  249,  250,  251,  252,  254,  255,  257,  258,
      259,  260,  262,  267
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "ly/scanner.ll"
/* $Id: scanner.ll 44 2008-10-23 09:03:19Z tb $ -*- mode: c++ -*- */
/** \file scanner.ll Define the example Flex lexical scanner */
#line 24 "ly/scanner.ll"

#include <string>

#include "../asm_token.h"
#define YYSTYPE asm_token


#include "scanner.h"

/* import the parser's token type into a local typedef */
typedef asm_lex_stuff::Parser::token token;
typedef asm_lex_stuff::Parser::token_type token_type;

/* By default yylex returns int, we use token_type. Unfortunately yyterminate
 * by default returns 0, which is not of token_type. */
#define yyterminate() return token::END

/* This disables inclusion of unistd.h, which is not available under Visual C++
 * on Win32. The C++ scanner uses STL streams instead. */
#define YY_NO_UNISTD_H


#define TOKEN_DEFAULT_AC(tp,resv,vnum )   \
    { \
       yylval->m_resolved=resv; \
       yylval->num = vnum; \
       yylval->val_str=yytext; \
       yylval->line_no=yylloc->begin.line; \
       yylval->column_no=yylloc->begin.column; \
       yylval->type=tp; \
       return tp;\
    }

/*** Flex Declarations and Options ***/
/* enable c++ scanner class generation */
/* change the name of the scanner class. results in "ExampleFlexLexer" */
/* the manual says "somewhat more optimized" */
/* enable scanner to generate debug output. disable this for release
 * versions. */
/* no support for include files is planned */
/* enables the use of start condition stacks */
/* The following paragraph suffices to track locations accurately. Each time
 * yylex is invoked, the begin position is moved onto the end position. */
#line 83 "ly/scanner.ll"
#define YY_USER_ACTION  yylloc->columns(yyleng);
#line 877 "scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#include <unistd.h>
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 86 "ly/scanner.ll"


 /* code to place at the beginning of yylex() */

    // reset location
    yylloc->step();


 /*** BEGIN EXAMPLE - Change the example lexer rules below ***/


#line 1051 "scanner.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin = & std::cin;
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout = & std::cout;
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 312 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 311 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 115 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 115 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 116 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 97 "ly/scanner.ll"
{ skip_comment(); TOKEN_DEFAULT_AC( token::EOL,1,0);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 99 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC(token::TK_ACC,1,0);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 100 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_C,1,0);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_AB,1,0);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_AT_DPTR,1,0);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_DPTR,1,0);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 104 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_AT_A_PLUS_PC,1,0);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_AT_A_PLUS_DPTR,1,0);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "ly/scanner.ll"
{ yylval->num = 0;  TOKEN_DEFAULT_AC( token::TK_AT_RI,1,0);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "ly/scanner.ll"
{ yylval->num = 1; TOKEN_DEFAULT_AC( token::TK_AT_RI,1,1);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 108 "ly/scanner.ll"
{yylval->num = 0; TOKEN_DEFAULT_AC( token::TK_RN,1,0);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 109 "ly/scanner.ll"
{yylval->num = 1; TOKEN_DEFAULT_AC( token::TK_RN,1,1);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 110 "ly/scanner.ll"
{yylval->num = 2; TOKEN_DEFAULT_AC( token::TK_RN,1,2);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 111 "ly/scanner.ll"
{yylval->num = 3; TOKEN_DEFAULT_AC( token::TK_RN,1,3);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 112 "ly/scanner.ll"
{yylval->num = 4; TOKEN_DEFAULT_AC( token::TK_RN,1,4);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 113 "ly/scanner.ll"
{yylval->num = 5; TOKEN_DEFAULT_AC( token::TK_RN,1,5);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 114 "ly/scanner.ll"
{yylval->num = 6; TOKEN_DEFAULT_AC( token::TK_RN,1,6);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 115 "ly/scanner.ll"
{yylval->num = 7; TOKEN_DEFAULT_AC( token::TK_RN,1,7);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 119 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 120 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 121 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 122 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 123 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 124 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 125 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 126 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 127 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 128 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 129 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 130 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 131 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 132 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 133 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 134 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 135 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 136 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 137 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 138 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 139 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 140 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 141 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 142 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 143 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 144 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 145 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 146 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 147 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 148 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 149 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 150 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 151 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 152 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 153 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 154 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 156 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 157 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 158 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 159 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 160 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 161 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 162 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 163 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 164 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_CMD,1,0);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 166 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_DB,1,0);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 167 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 168 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 169 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 170 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 171 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 172 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 173 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 174 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 175 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 176 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::TK_MACRO,1,0);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 179 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_DOLLAR,1,0);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 180 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_NOT,1,0);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 181 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_HIGH,1,0);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 182 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_LOW,1,0);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 183 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_SHL,1,0);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 184 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_MOD,1,0);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 186 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_SHIFT_RIGHT,1,0);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 187 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::TK_SHIFT_LEFT,1,0);}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 189 "ly/scanner.ll"
{TOKEN_DEFAULT_AC( token::EOL,1,0);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 191 "ly/scanner.ll"
{ /*各种标识符，修饰符等*/   TOKEN_DEFAULT_AC( token::TK_KEYWORD,0,0);



                            //{D}+{E}{FS}?				{ TOKEN_DEFAULT_AC( token::F_CONSTANT,0,0); }
                            //{D}*"."{D}+{E}?{FS}?			{ TOKEN_DEFAULT_AC( token::F_CONSTANT,0,0); }
                            //{D}+"."{E}?{FS}?			{ TOKEN_DEFAULT_AC( token::F_CONSTANT,0,0); }
                            //{HP}{H}+{P}{FS}?			{ TOKEN_DEFAULT_AC( token::F_CONSTANT,0,0); }
                            //{HP}{H}*"."{H}+{P}{FS}?			{ TOKEN_DEFAULT_AC( token::F_CONSTANT,0,0); }
                            //{HP}{H}+"."{P}{FS}?			{ TOKEN_DEFAULT_AC( token::F_CONSTANT,0,0); }


                            //({H}+{IS}?("H"|"h"))*"."{D}+{E}?{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //({H}+{IS}?("H"|"h"))+"."{E}?{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //({H}+{IS}?("H"|"h"))*"."{H}+{P}{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //({H}+{IS}?("H"|"h"))*"."{P}{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }


                            //([0-1]+{IS}?("B"|"b"))*"."{D}+{E}?{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //([0-1]+{IS}?("B"|"b"))+"."{E}?{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //([0-1]+{IS}?("B"|"b"))*"."{H}+{P}{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //([0-1]+{IS}?("B"|"b"))*"."{P}{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }

                            //{L}{A}*"."{D}+{E}?{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //{L}{A}+"."{E}?{FS}?				{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //{L}{A}*"."{H}+{P}{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }
                            //{L}{A}*"."{P}{FS}?			{ TOKEN_DEFAULT_AC( token::TK_BIT_PT,0,0); }

                            }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 224 "ly/scanner.ll"
{  TOKEN_DEFAULT_AC( token::I_CONSTANT,1,0); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 225 "ly/scanner.ll"
{  TOKEN_DEFAULT_AC( token::I_CONSTANT,1,0); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 226 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::I_CONSTANT,1,0); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 227 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::I_CONSTANT,1,0); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 228 "ly/scanner.ll"
{  TOKEN_DEFAULT_AC( token::I_CONSTANT,1,0); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 229 "ly/scanner.ll"
{  TOKEN_DEFAULT_AC( token::I_CONSTANT,1,0); }
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 233 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( token::STRING_LITERAL,1,0); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 237 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('.'),1,0); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 238 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('&'),1,0); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 239 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('!'),1,0); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 240 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('~'),1,0); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 242 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('-'),1,0); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 243 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('+'),1,0); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 244 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('*'),1,0); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 245 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('/'),1,0); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 247 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('%'),1,0); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 248 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('<'),1,0); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 249 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('>'),1,0); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 250 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('^'),1,0); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 251 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('|'),1,0); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 252 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('?'),1,0); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 254 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('('),1,0); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 255 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>(')'),1,0); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 257 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>(','),1,0); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 258 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>(':'),1,0); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 259 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('='),1,0); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 260 "ly/scanner.ll"
{ TOKEN_DEFAULT_AC( static_cast<token_type>('#'),1,0); }
	YY_BREAK
case 113:
/* rule 113 can match eol */
YY_RULE_SETUP
#line 262 "ly/scanner.ll"
{ /* whitespace separates tokens */ }
	YY_BREAK
/* pass all other characters up to bison */
case 114:
YY_RULE_SETUP
#line 267 "ly/scanner.ll"
{/* discard bad characters */
    //return static_cast<token_type>(*yytext);
}
	YY_BREAK
/*** END EXAMPLE - Change the example lexer rules above ***/
case 115:
YY_RULE_SETUP
#line 273 "ly/scanner.ll"
ECHO;
	YY_BREAK
#line 1770 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	ASMfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	ASMfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ASMrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ASMrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 312 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 312 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 311);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, register char* yy_bp)
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream* input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ASMalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ASMalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ASMfree((void *) b->yy_ch_buf  );

	ASMfree((void *) b  );
}

/* %if-c-only */
/* %endif */

/* %if-c++-only */

extern "C" int isatty (int );

/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ASMalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ASMrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) ASMalloc(new_size  );

		else
			(yy_start_stack) = (int *) ASMrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ASMalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ASMrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ASMfree (void * ptr )
{
	free( (char *) ptr );	/* see ASMrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 273 "ly/scanner.ll"



namespace asm_lex_stuff {

Scanner::Scanner(std::istream* in,
		 std::ostream* out)
    : ASMFlexLexer(in, out)
{
}

Scanner::~Scanner()
{
}

void Scanner::set_debug(bool b)
{
    yy_flex_debug = b;
}


void Scanner::skip_comment(void)
{
    int c;

    while ((c = yyinput()) != 0)
	{
        if (c == '\n')
        {
            
                return;
		}
	}
    std::cout<<"ERROR:"<<"unterminated comment"<<"line:"<<lineno();
}


}

/* This implementation of ASMFlexLexer::yylex() is required to fill the
 * vtable of the class ASMFlexLexer. We define the scanner's main yylex
 * function via YY_DECL to reside in the Scanner class instead. */

#ifdef yylex
#undef yylex
#endif

int ASMFlexLexer::yylex()
{
    std::cerr << "in ASMFlexLexer::yylex() !" << std::endl;
    return 0;
}

/* When the scanner receives an end-of-file indication from YY_INPUT, it then
 * checks the yywrap() function. If yywrap() returns false (zero), then it is
 * assumed that the function has gone ahead and set up `yyin' to point to
 * another input file, and scanning continues. If it returns true (non-zero),
 * then the scanner terminates, returning 0 to its caller. */

int ASMFlexLexer::yywrap()
{
    return 1;
}

