name: C/C++ CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ubuntu-install flex
      run: |
         sudo apt-get install libfl-dev -y
         sudo apt-get install flex bison -y

    - uses: actions/checkout@v2
    - name: make
      run: make all

